[lastfm]
user_name = "foobar"
password = "hunter2"
# Create these here: http://www.last.fm/api/account/create
api_key = "..."
api_secret = "..."

[chromecast]
name = "Living Room"
# (optional) list of chrome cast apps to scrobble from
app_whitelist = ["Spotify", "Google Play Music"]
